%YAML:1.0
# data
# the kitti dataset directory, change it to yours!
dataset_dir: /home/slam/datasets/kitti/00/
ground_truth_pose: /home/slam/datasets/kitti/ground-truth-poses/poses/00.txt

# camera intrinsics
# fr1
camera.fx: 7.188560000000e+02
camera.fy: 7.188560000000e+02
camera.cx: 6.071928000000e+02
camera.cy: 1.852157000000e+02

# VO paras
number_of_features: 500
scale_factor: 1.2
level_pyramid: 8
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
key_frame_min_rot: 0.1
key_frame_min_trans: 0.1
