%YAML:1.0
# data
# the kitti dataset directory, change it to yours!
dataset_dir: /home/slam/datasets/kitti/00/
ground_truth_pose: /home/slam/datasets/kitti/ground-truth-poses/poses/00.txt

# camera intrinsics
# fr1
camera.fx: 718.856
camera.fy: 718.856
camera.cx: 607.1928
camera.cy: 185.2157

camera.base_line: 0.573

# VO paras
number_of_features: 500
scale_factor: 1.2
level_pyramid: 8
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
key_frame_min_rot: 0.2
key_frame_min_trans: 1.5

#image paras
image.width: 1241
image.height: 376
image.gridSize: 40
